### PR TITLE
Refactor Footer Text Semantics and Update Styles for Consistency - Issue #32

### PR DESCRIPTION
**Pull request by imkrishnasarathi**
## Issue
Closes Issue #32 

## Changes Proposed
This PR Changes the footer section of the `index.html` to have the text contained in a `<p>` tag instead of a `<h4>` tag to make it meaningful semantically. It also includes the `<p>` tag mentioned above in the heading styles section in `styles.css` to maintain the same style as it was before.

## Screenshots
image
image

### CODE REVIEW

**Comment by jasonetorres** [comment]
Will review from desktop today.

**Review by michaella23 — APPROVED** [review]
Thank you for your attention to semantics! Approving this PR.

**Comment by imkrishnasarathi** [comment]
> Thank you for your attention to semantics! Approving this PR.

Awesome! Thank you Micha!

**Comment by michaella23** [comment]
I had approved this PR before #35 was merged, so had to resolve a conflict. Krishna had created addressed the issue #32 
 with a `p` and added an `id` to use for styling.

**Pull request merged**
