### PR TITLE
updated the themes and footer

### LINKED ISSUE #23: feat: add dark & light mode
## Suggestion
It'd be awesome for people to have a way people to view the website without straining their eyesight. 
## Describe the solution you'd like

Adding a dark/light mode toggle 

## Describe alternatives you've considered
N/A.

 ## Additional context
N/A

### LINKED ISSUE #32: [BUG](accessibility): footer text html tag
**Describe the bug**
The footer text is an `h4.` Semantically this does not make sense and it means headings are not in sequentially-descending order. 

**Expected behavior**
I would expect the footer text to be a simple `<p>` tag, _however_, if you'd like to keep it as a heading, make it an `h2`.

### PR DESCRIPTION
**Pull request by Ham12-3**
Issue #23: Implement Dark and Light Theme Toggle
Description:
Closes #23

Users should have the option to toggle between dark and light themes for better user experience, especially during different times of the day. The theme toggle will use a sun and moon icon to represent light and dark modes respectively.

Changes proposed:
Add a theme toggle icon that switches between light and dark modes. Use the Font Awesome icons fa-moon for dark mode and fa-sun for light mode.
Implement CSS variables to manage the styles for both dark and light modes.
Save the selected theme in localStorage so it persists between sessions.
On page load, check localStorage for the user's preferred theme and apply it.
Update the icon based on the active theme.
Screenshots:
Add screenshots showing:

image
image

https://github.com/user-attachments/assets/df529691-4d6c-4301-a83c-893f1f817e30

Note to reviewers:
Ensure that the theme toggle works smoothly.
Confirm that the user's preference is stored and persists after reloading the page.

Issue #32: Dynamic Footer Year
Description:
Closes #32

The footer should display the current year dynamically to avoid manual updates. This ensures that the copyright notice is always accurate.

Changes proposed:
Add JavaScript to automatically insert the current year in the footer.
Ensure that the year is updated correctly on January 1st each year.
Screenshots:
image

Note to reviewers:
Confirm that the footer year updates automatically based on the current date.
Test on different browsers to ensure compatibility.

### CODE REVIEW

**Comment by jasonetorres** [comment]
now this is a PR submission, wow!

**Comment by CBID2** [comment]
Hey @Ham12-3. I did the dark mode in [here](https://github.com/TheTechCommute/TheTechCommute/pull/28). If you're open, I can raise a separate issue for the footer.

**Comment by Ham12-3** [comment]
I am still open so can I close or are you merging

**Comment by CBID2** [comment]
> I am still open so can I close or are you merging

Merging.

**Comment by Ham12-3** [comment]
Ok, merge

**Review by michaella23 — CHANGES_REQUESTED** [review]
Hello @Ham12-3! thanks for all the work you did on this issue. 
I appreciated several things about your PR:
- the detailed description and screenshots you included
- how you have formatted code to make it more readable
- the UI improvements
We have merged a few other PRs since you submitted this and so now we have some conflicts that have come up. Would be happy to merge your changes if you could resolve those first.
Thank you!

**Comment by Ham12-3** [comment]
I am deeply sorry for replying you late. I have merged it already from my side

**Review by michaella23 — APPROVED** [review]
Thanks for resolving the merge conflicts @Ham12-3, and thanks for your contribution. Enjoy your holopin! https://holopin.io/collect/cm297v5hw18430cl1rosd4p5s

**Pull request merged**
