### PR TITLE
feat: adding light and dark mode

### LINKED ISSUE #23: feat: add dark & light mode
## Suggestion
It'd be awesome for people to have a way people to view the website without straining their eyesight. 
## Describe the solution you'd like

Adding a dark/light mode toggle 

## Describe alternatives you've considered
N/A.

 ## Additional context
N/A

### PR DESCRIPTION
**Pull request by CBID2**
## Issue

Closes #23 
## Changes proposed 

I used [Darkmodejs](https://darkmodejs.learn.uno/) to add the dark mode effect. 

## Screenshots/Videos 

https://github.com/TheTechCommute/TheTechCommute/assets/105683440/8fbf5447-6586-421d-8e8d-77206adc8dfe

### CODE REVIEW

**Comment by CBID2** [comment]
Hey @jasonetorres! :) My PR is ready for review! :)

**Review by evenstensberg — COMMENTED** [review]
Would be nice if you squashed your commits. `git rebase -i HEAD~xCommits`

**Comment by CBID2** [comment]
> Would be nice if you squashed your commits. `git rebase -i HEAD~xCommits`

I'll consider that

**Comment by jasonetorres** [comment]
> > Would be nice if you squashed your commits. `git rebase -i HEAD~xCommits`
> 
> I'll consider that 

Lmk when you did that and I'll review again and merge! Thanks, nice work.

**Comment by CBID2** [comment]
> > > Would be nice if you squashed your commits. `git rebase -i HEAD~xCommits`
> > 
> > 
> > I'll consider that
> 
> Lmk when you did that and I'll review again and merge! Thanks, nice work.

Hey @jasonetorres. I squashed my commits

**Comment by jasonetorres** [comment]
thanks @CBID2  enjoy your @holopin
https://holopin.io/collect/cm297v5hw18430cl1rosd4p5s

**Comment by CBID2** [comment]
> thanks @CBID2  enjoy your @holopin
> 
> https://holopin.io/collect/cm297v5hw18430cl1rosd4p5s

Thanks @jasonetorres! :) Feel free to reopen my PR. I closed it because I thought I wasn't assigned it anymore

**Comment by michaella23** [comment]
Closing this for now since dark mode was added in another PR. Thanks for working on this @CBID2!

**Pull request closed without merging**
